[package]
name = "zhhz-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
zhhz = { path = ".." }
libfuzzer-sys = "0.4"

[[bin]]
name = "fmm_segment"
path = "fuzz_targets/fmm_segment.rs"

[[bin]]
name = "convert_roundtrip"
path = "fuzz_targets/convert_roundtrip.rs"
